request:
  cookieValidationKey: LPvaIkHkLq1uSK1TcFPP4dntWWIyfmq_
cache:
  class: yii\caching\FileCache
errorHandler:
  errorAction: site/error
log:
  traceLevel: !interpret 'YII_DEBUG ? 3 : 0'
  targets:
    - class: yii\log\FileTarget
      levels:
        - error
        - warning
urlManager:
  enablePrettyUrl: true
  showScriptName: false
  rules: { }
orm:
  class: Moneyman\App\Cycle\CycleAdapter
  dbConfigs: !env /orm_config